# PV 
{{- if and .Values.persistence.enabled (not .Values.persistence.existingClaim) }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "common.names.fullname" . }}
  labels: 
    name: pvc-portalsms
    volume-type: ssd 
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: {{ .Values.persistence.pv.fileshareServerIp | quote }}
    path: {{ .Values.persistence.pv.fileshareServerPath | quote }}
{{- end }}